kind: Deployment
apiVersion: apps/v1
metadata:
   name: my-dep
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod
       labels:
         name: deployment
     spec:
      containers:
        - name: c00
          image: 137855620426.dkr.ecr.ap-south-1.amazonaws.com/example:latest
          ports:
          - containerPort: 3000
